### ISSUE TITLE
Not supporting all Github actions

### ISSUE THREAD

**Issue by uKetki** [azu/migrate-travis-ci-to-github-actions#2]
I added the below `.travis.yml` file:
```
language: android

android:
  components:
    - tools                             # Tools
    - platform-tools                    # Platform tools
    - build-tools-28.0.3                # Build tools version
    - android-28                        # Target SDK version
    - extra-android-m2repository        # Support repo

jdk:
  - oraclejdk8

script:
  - ./gradlew build

branches:
  except:
    - gh-pages

notifications:
  email: false

cache:
  directories:
    - $HOME/.gradle
 ```

However, GitHub actions are generated only for a very limited functionality: 
```
name: test
on: [push, pull_request]
jobs:
  test:
    name: "Test on Node.js ${{ matrix.node-version }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12, 14]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: yarn install
      - name: Test
        run: yarn test
```
